Rename SHA1 macros to avoid conflicts with ucontext.h on ARM.
Fixes this cross-compilation error:

```
nlutils/src/sha1.c:108:1: error: "R0" redefined
arm-none-linux-gnueabi/libc/usr/include/sys/ucontext.h:44:1: error: this is the location of the previous definition
```

Introduced by https://github.com/nitrogenlogic/nlutils/pull/3